import = [
    # "~/.config/alacritty/themes/themes/one_dark.toml"
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
    ]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_title = true
#decorations = "Transparent"
decorations = "Buttonless"
opacity=0.8
blur = true

[selection]
save_to_clipboard = true

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "JetBrainsMonoNL Nerd Font"

#regular
size = 15

#for video
# size = 35.0
